# Generated by Django 4.2.11 on 2026-06-08 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITriageRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("urgency", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("emergency", models.BooleanField(default=False)),
                ("tenant_sumary", models.TextField()),
                ("staff_recommendation", models.TextField()),
                ("raw_response", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_requests",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Triage Request",
                "verbose_name_plural": "AI Triage Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
