# Generated by Django 4.2.11 on 2026-06-08 09:05

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_phase1_roles_and_scoping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city_of_origin",
            field=models.CharField(
                default="Orlando", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                default="US", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+4075558754",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
